---
application:
  properties:
    botAdminId: ${BOT_ADMIN:}
    botToken: ${BOT_TOKEN:}
    botUsername: ${BOT_USERNAME:}
  scheduler:
    enabled: ${SCHEDULER_ENABLED:false}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized
    info:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,env,beans,loggers,prometheus
      path-mapping:
        health: healthcheck
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: padelscore-bot
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD:}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/padelscore}
    username: ${SPRING_DATASOURCE_USERNAME:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    operations-sorter: method
    path: /swagger-ui.html
    tags-sorter: alpha
    try-it-out-enabled: true

telegram:
  bot:
    token: ${BOT_TOKEN:}
    username: ${BOT_USERNAME:}

telegrambots:
  enabled: true
...
